
    drop table subject_role if exists;

    drop table `user` if exists;

    create table subject_role (
        id integer generated by default as identity,
        created_at timestamp not null,
        last_updated_at timestamp not null,
        type varchar(255) not null,
        user_id integer not null,
        primary key (id)
    );

    create table `user` (
        id integer generated by default as identity,
        birthday date,
        city_id bigint,
        created_at timestamp not null,
        district_id bigint,
        email varchar(190) not null,
        external_id varchar(255),
        first_name varchar(40) not null,
        gender varchar(255),
        last_name varchar(40) not null,
        last_updated_at timestamp not null,
        password varchar(255) not null,
        permit_email boolean,
        permit_notification boolean,
        permit_sms boolean,
        phone_number varchar(190),
        registration_channel varchar(255),
        salt varchar(255),
        town_id bigint,
        primary key (id)
    );

    alter table `user` 
        add constraint user_email_uk unique (email);

    alter table `user` 
        add constraint user_phone_number_uk unique (phone_number);
